nodeLinker: node-modules

npmRegistryServer: 'https://nexus.sdl.com/repository/npm/'

npmScopes:
    tridion-sites:
        npmPublishRegistry: 'https://nexus.sdl.com/repository/npm-internal/'
        npmRegistryServer: 'https://nexus.sdl.com/repository/npm-internal/'
